import { API_URL } from "../utils";

export const apiRoutes = {
  login: `${API_URL}/auth/signin`,
  logout: `${API_URL}/logout`,
  users: `${API_URL}/users`,
  orders: `${API_URL}/shop/getOrderByStore`,
  reviews: `${API_URL}/unknown`,
  deleteUser: `${API_URL}/user`,
  getDeposit: `${API_URL}/profile/history-payments`,
  getWithdraw: `${API_URL}/profile/history-withdraws`,
  getUserKyc: `${API_URL}/users-kyc`,
  getUserJoin: `${API_URL}/getVerifyCTV`,
  handleKyc: `${API_URL}/user-kyc`,
  getStatisticsPayment: `${API_URL}/statistics-payment`,
  handleWithdraw: `${API_URL}/handle-withdraw`,
  handleDeleteTransaction: `${API_URL}/delete-transaction`,
  handleDeposit: `${API_URL}/handle-deposit`,
  handleVerifyCTV: `${API_URL}/handleVerifyCTV`,
  historyBet: `${API_URL}/histories-bet`,
  historyBetFuture: `${API_URL}/histories-bet-future`,
  historyInvest: `${API_URL}/histories-invest`,
  updateUser: `${API_URL}/update-user`,
  getAdmin: `${API_URL}/profile/me`,
  getAnalyticData: `${API_URL}/analytic`,
  updateBet: `${API_URL}/update-bet`,
  dashboarData: `${API_URL}/profile/getDataShop`,
  addBank: `${API_URL}/add-bank`,
  deleteBank: `${API_URL}/delete-bank`,
  updateBank: `${API_URL}/update-bank`,
  getBanks: `${API_URL}/banks`,
  updateBetFuture: `${API_URL}/updateHistoryFuture`,
  handleUpdateWithdraw: `${API_URL}/handleUpdateWithdraw`,
};
