export const webRoutes = {
  home: '/',
  login: '/login',
  logout: '/logout',
  dashboard: '/dashboard',
  users: '/users',
  orders: '/orders',
  detailPay: '/detail-pay',
  deposit: '/deposit',
  withdraw: '/withdraw',
  history_bet: '/histories-bet',
  history_bet_future: '/histories-bet-future',
  history_invest: '/histories-invest',
  about: '/about',
  bet: '/bet',
  kyc: '/kyc',
  ref: '/ref',
  setting: '/setting',
};
